name: CI

on:
  push:
    branches: [next]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        runner: [ubuntu-latest, windows-latest, macos-14]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            nx_ci_execution_env: linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            nx_ci_execution_env: windows
          - os: macos-14
            target: aarch64-apple-darwin
            nx_ci_execution_env: macos

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    env:
      NX_CI_EXECUTION_ENV: ${{ matrix.nx_ci_execution_env }}
      NX_BRANCH: ${{ github.event.pull_request.head.ref || github.ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Cache cargo if Rust
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Cache the `oxide` Rust build
      - name: Cache oxide build
        uses: actions/cache@v4
        with:
          path: |
            ./target/
            ./crates/node/*.node
            ./crates/node/index.js
            ./crates/node/index.d.ts
          key: ${{ runner.os }}-oxide-${{ hashFiles('./crates/**/*') }}

      # Install Rust
      - name: Install Rust (Stable)
        run: rustup default stable

      - name: Setup rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies
        run: pnpm install

      # Nx Cloud start-ci-run using windows or linux agents accordingly
      - run: npx nx-cloud start-ci-run --distribute-on="3 tailwind-${{ matrix.nx_ci_execution_env }}-rust" --stop-agents-on-failure=false --stop-agents-after="integration-test"
        if: matrix.nx_ci_execution_env != 'macos'

      # Nx Cloud does not support macOS agents yet, so we need to use local agents for now
      - run: npx nx-cloud start-ci-run --stop-agents-on-failure=false --stop-agents-after="integration-test"
        if: matrix.nx_ci_execution_env == 'macos'

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'next'

      # Nx Affected command build
      - name: Run affected for build except playgrounds
        run: npx nx affected -t=build --parallel=3 --exclude=nextjs-playground,vite-playground,@tailwindcss/root

      - name: Run affected for postbuild except playgrounds
        run: npx nx affected -t=postbuild

      - name: Run affected for lint
        run: npx nx run-many -t=build --projects@tailwindcss/node,@tailwindcss/oxide && npx prettier --check . && npx nx affected -t=lint --exclude nextjs-playground,vite-playground,@tailwindcss/root

      - name: Run affected for Playwright tests
        run: npx nx affected -t=build --projects@tailwindcss/node,@tailwindcss/oxide && npx playwright install --with-deps && npx nx affected -t=test:ui

      # Nx Affected command for tests
      - name: Run affected for tests
        run: npx nx run-many -t=build --projects@tailwindcss/node && npx nx affected -t=test --parallel=3

      # # Nx Affected command for integration tests
      - name: Run affected for integration tests
        run: npx nx run-many -t=build --projects@tailwindcss/standalone && npx nx affected -t=postbuild && npx nx affected -t=integration-test --parallel=3


  macos-dte-agents:
    name: MacOS DTE Agent
    runs-on: macos-14
    timeout-minutes: 30

    env:
      NX_CI_EXECUTION_ENV: macos
      NX_BRANCH: ${{ github.event.pull_request.head.ref || github.ref }}

    strategy:
      matrix:
        node-version: [20]
        agent: [1, 2, 3]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Cache cargo if Rust
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      # Cache the `oxide` Rust build
      - name: Cache oxide build
        uses: actions/cache@v4
        with:
          path: |
            ./target/
            ./crates/node/*.node
            ./crates/node/index.js
            ./crates/node/index.d.ts
          key: ${{ runner.os }}-oxide-${{ hashFiles('./crates/**/*') }}

      # Install Rust
      - name: Install Rust (Stable)
        run: rustup default stable

      - name: Setup rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwrite
        run: pnpm exec playwright install --with-deps

      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
        env:
          NX_AGENT_NAME: ${{ matrix.agent }}
